<a href="https://colab.research.google.com/github/Takada-machine12/ML_Practice/blob/main/Takada-machine12/ML_Practice/Practice_code/Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# mglearnインストール
!pip install mglearn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 581.4/581.4 kB 9.9 MB/s eta 0:00:00


In [ ]:
# 必要なライブラリのインポート
import sys
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy as sp
import mglearn
from IPython.display import display
# グラフをブラウザ上に直接表示するコマンド
%matplotlib inline

In [ ]:
# データ読み込み
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [ ]:
# データ表示
print("Key of iris_dataset: \n{}".format(iris_dataset.keys()))

Key of iris_dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
# データセットの簡単な説明の最初の部分を確認(DESCR)
print(iris_dataset['DESCR'][:193] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive 
...


In [ ]:
# 予測しようとしている花の種類
print("Target names: {}".format(iris_dataset['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


In [ ]:
# 花の特徴量
print("Feature names: {}".format(iris_dataset['feature_names']))

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
# データの詳細
print("Type of data: {}".format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


In [ ]:
# データの形(行,列)
print("Shape of data: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


In [ ]:
# 最初の5つのサンプルを確認
print("First five column of data: {}".format(iris_dataset['data'][:5]))

First five column of data: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
# 測定された個々の花の種類
print("Type of target: {}".format(type(iris_dataset['target'])))

Type of target: <class 'numpy.ndarray'>


In [ ]:
# データの形
print("Shape of target: {}".format(iris_dataset['target'].shape))

Shape of target: (150,)


In [ ]:
# targetの中身確認
print("Target:\n{}".format(iris_dataset['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
